### PR TITLE
API Ordering for tasks, task lists, subtasks and notes.

### PR DESCRIPTION
**Pull request by franciscoj**
# What

This parameter is the one which is meant to be used to keep order.
`position` is a "write only" parameter.

# What to test

Lists returned can be sorted by using the `row_order` parameter.

# GIF

### CODE REVIEW

**Comment by andrius** [comment]
Looks fine!

**Comment by bpedro** [comment]
:+1:

**Comment by jrom** [comment]
So `row_order` to read and `position` to write? Why do we need 2 different concepts?

**Comment by masylum** [comment]
Its a long story, but summarizing: Relative position in a DB is an anti-pattern:

  - It requires N updates on adding an element where N is all the siblings below you
  - If positions are duplicated (race conditions happen) the whole list is corrupted
  - It relies heavily in side effects since updating the position of one element means updating other's position.

By separating a setter and a getter we can overcome this. `row_order` is an attribute and setting the position is a `RPC` action.

**Comment by masylum** [comment]
:+1:

**Pull request merged**
